import React,{useEffect,useState} from 'react';
import {ArrowRight,Loader2,MessageCircle,Sparkles} from 'lucide-react';
import {request} from '../../services/studyApi';
import {TurboStudyPack} from '../../types/turbo';
export function StudyChat({pack}:{pack:TurboStudyPack}){
  const [messages,setMessages]=useState<any[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(pack.id==='blast-example')return;request(`/notebooks/${pack.id}/chat`).then(d=>setMessages(d.messages)).catch(e=>setError(e.message));},[pack.id]);
  async function send(){if(!input.trim()||busy)return;const message=input.trim();setBusy(true);setError('');try{const result=await request(`/notebooks/${pack.id}/chat`,{method:'POST',body:JSON.stringify({message})});setMessages(prev=>[...prev,{role:'user',message},{role:'assistant',...result}]);setInput('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  return <><div className="panel-heading"><div><span className="eyebrow">LET’S WORK IT OUT</span><h2>A tutor for this notebook</h2><p>Ask a follow-up, work through an example, or check your understanding.</p></div><MessageCircle size={25}/></div>{pack.id==='blast-example'?<p className="inline-error">Create a notebook from your own topic or sources to use the live tutor.</p>:<><div className="tutor-messages">{!messages.length&&<div className="tutor-welcome"><Sparkles size={23}/><h3>What would you like to understand?</h3><p>Your notes and source material stay in context.</p>{['Explain the main idea simply','Walk me through a worked example','What mistakes should I watch for?'].map(q=><button className="subtle-button" key={q} onClick={()=>setInput(q)}>{q}</button>)}</div>}{messages.map((m,i)=>m.role==='user'?<div className="tutor-user" key={i}>{m.message}</div>:<article className="tutor-answer" key={i}><span className="eyebrow">BLAST TUTOR</span><h3>{m.answer.title}</h3><p className="notes-intro">{m.answer.summary}</p>{m.answer.sections.map((s:any,j:number)=><section key={j}><h4>{s.heading}</h4><p>{s.content}</p><CitationLinks ids={s.sourceIds} citations={m.citations}/></section>)}<div className="tutor-check"><strong>Your turn</strong><p>{m.answer.checkQuestion}</p></div><CitationLinks ids={m.answer.sourceIds} citations={m.citations}/></article>)}</div><form className="tutor-composer" onSubmit={e=>{e.preventDefault();send();}}><textarea aria-label="Ask about this notebook" value={input} onChange={e=>setInput(e.target.value)} maxLength={4000} placeholder="Ask about your notes…" disabled={busy}/><button className="dark-button" disabled={busy||!input.trim()} aria-label="Send tutor question">{busy?<Loader2 className="spin" size={18}/>:<ArrowRight size={18}/>}</button></form>{error&&<p className="inline-error" role="alert">{error}</p>}</>}</>;
}
export function CitationLinks({ids,citations}:{ids?:string[];citations:any[]}){return <div className="citation-links">{[...new Set(ids||[])].map(id=>{const c=citations.find(x=>x.id===id);return c?<a key={id} href={`/api/documents/${c.documentId}/file#page=${c.page}`} target="_blank" rel="noopener noreferrer" title={c.excerpt||c.summary}>{c.title} · p. {c.page}</a>:null;})}</div>;}
