import React, { useEffect, useRef, useState } from 'react';
import { BookOpen, Layers, Compass, Headphones, HelpCircle, Check, Circle, CheckCircle2, Pencil, RotateCcw, ChevronLeft, ChevronRight, Sparkles, Play, Pause, ExternalLink } from 'lucide-react';
import { TurboStudyPack } from '../../types/turbo';
import { request } from '../../services/studyApi';
import { StudyChat, CitationLinks } from './StudyChat';
export type StudyTab = 'learn' | 'notes' | 'cards' | 'quiz' | 'audio' | 'sources' | 'chat';
export function progress(pack: TurboStudyPack) { const all = pack.roadmap?.stages?.flatMap(s => s.milestones) || []; return all.length ? Math.round(all.filter(m => m.completed).length / all.length * 100) : 0; }
export function readLocal<T>(key: string, fallback: T): T { try { return JSON.parse(localStorage.getItem(key) || 'null') ?? fallback; } catch { return fallback; } }
export function EmptyTool({ icon: Icon, title, description }: { icon: typeof BookOpen; title: string; description: string }) { return <div className="empty-state"><Icon size={30} /><h3>{title}</h3><p>{description}</p></div>; }

export function StudyTools({ pack, tab, save, notify }: { pack: TurboStudyPack; tab: StudyTab; save: (p: TurboStudyPack) => Promise<void>; notify: (s: string) => void }) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState('');
  const [cardIndex, setCardIndex] = useState(0);
  const [flipped, setFlipped] = useState(false);
  const [answers, setAnswers] = useState<Record<string, number>>(() => readLocal(`blast_attempt_${pack.id}`, {}));
  const [audioState, setAudioState] = useState<'idle' | 'playing' | 'paused'>('idle');
  const [audioIndex, setAudioIndex] = useState(0);
  const [audioError, setAudioError] = useState('');
  const audioGeneration = useRef(0);
  const [reviews,setReviews]=useState<any[]>([]);
  useEffect(()=>{if(pack.id==='blast-example')return;request(`/notebooks/${pack.id}/progress`).then(d=>{setAnswers(d.answers);setReviews(d.reviews);}).catch(e=>notify(e.message));},[pack.id]);
  useEffect(() => () => { audioGeneration.current++; window.speechSynthesis?.cancel(); }, []);
  async function toggleMilestone(s: number, i: number) { const next = JSON.parse(JSON.stringify(pack)) as TurboStudyPack; const m = next.roadmap.stages[s].milestones[i]; m.completed = !m.completed; next.roadmap.overallProgress = progress(next); next.roadmap.stages.forEach(stage => { stage.progressPercent = Math.round(stage.milestones.filter(x => x.completed).length / (stage.milestones.length || 1) * 100); }); try { await save(next); } catch { notify('Could not save your progress. Browser storage may be full.'); } }
  async function answer(id: string, index: number) { const next = { ...answers, [id]: index }; try { if(pack.id!=='blast-example')await request(`/notebooks/${pack.id}/answers`,{method:'PUT',body:JSON.stringify(next)});else localStorage.setItem(`blast_attempt_${pack.id}`, JSON.stringify(next)); setAnswers(next); } catch { notify('Could not save your quiz progress.'); } }
  function speak(index: number) { if (!('speechSynthesis' in window)) { setAudioError('Read-aloud is not supported here. The transcript is available below.'); return; } const segments = pack.podcast.segments; if (index >= segments.length) { setAudioState('idle'); setAudioIndex(0); return; } const generation = ++audioGeneration.current; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(segments[index].line); utterance.rate = 0.95; utterance.onend = () => { if (generation === audioGeneration.current) speak(index + 1); }; utterance.onerror = e => { if (generation === audioGeneration.current && e.error !== 'canceled' && e.error !== 'interrupted') { setAudioState('idle'); setAudioError('Playback could not start. You can still read the transcript.'); } }; setAudioIndex(index); setAudioState('playing'); window.speechSynthesis.speak(utterance); }
  function toggleAudio() { if (audioState === 'playing') { window.speechSynthesis.pause(); setAudioState('paused'); } else if (audioState === 'paused') { window.speechSynthesis.resume(); setAudioState('playing'); } else speak(audioIndex); }
  const empty = (icon: typeof BookOpen, title: string) => <EmptyTool icon={icon} title={title} description="Generate study activities from your notes when you’re ready." />;
  async function rateCard(rating:string){try{if(pack.id==='blast-example'){notify('Review scheduling is available in your own notebooks.');return;}const review=await request(`/notebooks/${pack.id}/reviews`,{method:'POST',body:JSON.stringify({card:pack.flashcards.cards[cardIndex].id,rating})});setReviews(prev=>[review,...prev.filter(x=>x.card!==review.card)]);notify('Next review: '+new Date(review.due).toLocaleString());setFlipped(false);setCardIndex((cardIndex+1)%pack.flashcards.cards.length);}catch(e:any){notify(e.message);}}
  return <>
    {tab==='chat'&&<StudyChat pack={pack}/>}
    {tab === 'learn' && <><div className="panel-heading"><div><span className="eyebrow">ONE STEP AT A TIME</span><h2>Your path to understanding</h2><p>{pack.roadmap.targetGoal || 'A little structure for your next discovery.'}</p></div><span className="progress-ring" style={{ '--progress': `${progress(pack)}%` } as React.CSSProperties}><span>{progress(pack)}<small>%</small></span></span></div>{pack.roadmap.stages.length ? pack.roadmap.stages.map((stage, s) => <div className="roadmap-stage" key={stage.id}><div className="stage-heading"><span>{String(s + 1).padStart(2, '0')}</span><div><h3>{stage.stageName}</h3><p>{stage.description}</p></div></div>{stage.milestones.map((m, i) => <div className={`milestone ${m.completed ? 'complete' : ''}`} key={m.id}><button className="milestone-check" aria-label={`${m.completed ? 'Mark incomplete' : 'Complete'}: ${m.title}`} aria-pressed={m.completed} onClick={() => toggleMilestone(s, i)}>{m.completed ? <CheckCircle2 size={23} /> : <Circle size={23} />}</button><div><h4>{m.title}</h4><p>{m.tasks.join(' ')}</p><div className="concept-tags">{m.keyConcepts.map(c => <span key={c}>{c}</span>)}</div></div><span className="duration">{m.duration}</span></div>)}</div>) : empty(Compass, 'Your learning path starts here')}</>}
    {tab === 'notes' && <><div className="panel-heading"><div><span className="eyebrow">THE BIG PICTURE</span><h2>{pack.notes.title}</h2></div><button className="subtle-button" onClick={async () => { if (editing) { try { await save({ ...pack, notes: { ...pack.notes, sections: [{ heading: 'Study notes', content: draft }], lastUpdated: new Date().toISOString() } }); setEditing(false); notify('Your edits are saved.'); } catch { notify('Could not save your edits. Browser storage may be full.'); } } else { setDraft(pack.notes.sections.map(s => `${s.heading}\n\n${s.content}\n${(s.bulletPoints || []).map(b => `• ${b}`).join('\n')}\n${(s.formulas || []).join('\n')}${s.codeSnippet ? '\n' + s.codeSnippet.code : ''}`).join('\n\n')); setEditing(true); } }}>{editing ? <Check size={15} /> : <Pencil size={15} />}{editing ? 'Save changes' : 'Edit notes'}</button></div>{editing ? <><label className="field-label" htmlFor="note-editor">Your notes</label><textarea id="note-editor" className="notes-editor" value={draft} onChange={e => setDraft(e.target.value)} /><button className="text-button" onClick={() => setEditing(false)}>Discard changes</button></> : <div className="notes-layout"><article className="notes-prose"><p className="notes-intro">{pack.notes.summary}</p>{pack.notes.sections.map((s, i) => <section key={i}><h3>{s.heading}</h3><p>{s.content}</p>{!!s.bulletPoints?.length && <ul>{s.bulletPoints.map((b, j) => <li key={j}>{b}</li>)}</ul>}{s.formulas?.map((f, j) => <pre key={j}>{f}</pre>)}{s.codeSnippet && <pre><code>{s.codeSnippet.code}</code></pre>}<CitationLinks ids={s.sourceIds} citations={pack.sources}/></section>)}</article>{pack.notes.keyTakeaways.length > 0 && <aside className="takeaways"><Sparkles size={20} /><h3>Keep these in mind</h3>{pack.notes.keyTakeaways.map((t, i) => <p key={i}><span>{String(i + 1).padStart(2, '0')}</span>{t}</p>)}</aside>}</div>}</>}
    {tab === 'cards' && <><div className="panel-heading"><div><span className="eyebrow">A LITTLE ACTIVE RECALL</span><h2>Give your memory a moment</h2><p>Think of an answer. Then flip to check.</p></div><span className="pill neutral">{pack.flashcards.cards.length} cards</span></div>{pack.flashcards.cards.length ? <div className="flashcard-area"><div className="flashcard-topline"><span>{pack.flashcards.cards[cardIndex]?.category}</span><span>{cardIndex + 1} / {pack.flashcards.cards.length}</span></div><button className={`study-flashcard ${flipped ? 'flipped' : ''}`} onClick={() => setFlipped(!flipped)} aria-label={flipped ? 'Show question' : 'Reveal answer'}><span>{flipped ? 'THE ANSWER' : 'THINK ABOUT IT'}</span><h3>{flipped ? pack.flashcards.cards[cardIndex]?.back : pack.flashcards.cards[cardIndex]?.front}</h3><small><RotateCcw size={14} />{flipped ? 'Tap to see the question' : 'Tap to reveal'}</small></button>{flipped&&<div className="review-buttons"><button className="subtle-button" onClick={()=>rateCard('again')}>Again · 10 min</button><button className="subtle-button" onClick={()=>rateCard('good')}>Got it</button><button className="subtle-button" onClick={()=>rateCard('easy')}>Easy</button></div>}<p className="review-due">{reviews.find(r=>r.card===pack.flashcards.cards[cardIndex]?.id)?.due?'Next review: '+new Date(reviews.find(r=>r.card===pack.flashcards.cards[cardIndex]?.id).due).toLocaleString():'New card · ready to review'}</p><CitationLinks ids={pack.flashcards.cards[cardIndex]?.sourceIds} citations={pack.sources}/><div className="flashcard-controls"><button className="icon-button" aria-label="Previous card" disabled={cardIndex === 0} onClick={() => { setCardIndex(cardIndex - 1); setFlipped(false); }}><ChevronLeft size={19} /></button><div className="card-dots">{pack.flashcards.cards.map((c, i) => <button key={c.id} aria-label={`Go to card ${i + 1}`} className={i === cardIndex ? 'active' : ''} onClick={() => { setCardIndex(i); setFlipped(false); }} />)}</div><button className="icon-button" aria-label="Next card" disabled={cardIndex === pack.flashcards.cards.length - 1} onClick={() => { setCardIndex(cardIndex + 1); setFlipped(false); }}><ChevronRight size={19} /></button></div></div> : empty(Layers, 'A fresh deck is waiting')}</>}
    {tab === 'quiz' && <><div className="panel-heading"><div><span className="eyebrow">PROGRESS, NOT PERFECTION</span><h2>See what’s sticking</h2><p>Choose an answer to get immediate feedback.</p></div><button className="subtle-button" onClick={async () => { try { if(pack.id!=='blast-example')await request(`/notebooks/${pack.id}/answers`,{method:'PUT',body:'{}'});localStorage.removeItem(`blast_attempt_${pack.id}`); setAnswers({}); } catch { notify('Could not reset this attempt.'); } }}><RotateCcw size={15} />Start again</button></div>{pack.quiz.questions.length ? <><div className="quiz-summary"><span>{pack.quiz.questions.filter(q => answers[q.id] !== undefined).length} of {pack.quiz.questions.length} answered</span><strong>{pack.quiz.questions.filter(q => answers[q.id] === q.correctIndex).length} correct</strong></div>{pack.quiz.questions.map((q, i) => <div className="quiz-question" key={q.id}><span className="question-number">QUESTION {String(i + 1).padStart(2, '0')}</span><h3>{q.question}</h3><div className="quiz-options">{q.options?.map((o, j) => <button key={j} disabled={answers[q.id] !== undefined} className={answers[q.id] === undefined ? '' : j === q.correctIndex ? 'correct' : answers[q.id] === j ? 'incorrect' : ''} onClick={() => answer(q.id, j)}><span>{String.fromCharCode(65 + j)}</span>{o}{answers[q.id] !== undefined && j === q.correctIndex && <Check size={17} />}</button>)}</div>{answers[q.id] !== undefined && <div className="answer-explanation" role="status"><strong>{answers[q.id] === q.correctIndex ? 'You’ve got it.' : 'A useful learning moment.'}</strong> {q.explanation}<CitationLinks ids={q.sourceIds} citations={pack.sources}/></div>}</div>)}</> : empty(HelpCircle, 'Put your knowledge to the test')}</>}
    {tab === 'audio' && <><div className="panel-heading"><div><span className="eyebrow">LET IT SINK IN</span><h2>A fresh way to listen</h2><p>Read-aloud uses your browser’s voice.</p></div><span className="pill neutral">{pack.podcast.audioDurationEstimate || 'Audio recap'}</span></div>{pack.podcast.segments.length ? <><div className="audio-player"><div className={`audio-art ${audioState === 'playing' ? 'playing' : ''}`}><Headphones size={42} /><span /><span /><span /></div><h3>{pack.podcast.title}</h3><p>{pack.podcast.overview}</p><div className="audio-controls"><button className="icon-button" aria-label="Restart audio" onClick={() => speak(0)}><RotateCcw size={20} /></button><button className="audio-play" aria-label={audioState === 'playing' ? 'Pause audio' : 'Play audio'} onClick={toggleAudio}>{audioState === 'playing' ? <Pause size={23} /> : <Play size={23} fill="currentColor" />}</button><span>{audioIndex + 1} / {pack.podcast.segments.length}</span></div>{audioError && <p role="alert">{audioError}</p>}</div><h3 className="transcript-heading">Follow the conversation</h3>{pack.podcast.segments.map((s, i) => <button key={i} className={`transcript-line ${i === audioIndex && audioState !== 'idle' ? 'speaking' : ''}`} onClick={() => speak(i)}><span>{s.speaker}</span><p>{s.line}</p><Play size={14} /></button>)}</> : empty(Headphones, 'Your notes, read aloud')}</>}
    {tab === 'sources' && <><div className="panel-heading"><div><span className="eyebrow">FOLLOW YOUR CURIOSITY</span><h2>Further reading</h2><p>{pack.documentIds?.length?'Your original source material, with page references.':'No uploaded source material is attached to this notebook.'}</p></div></div>{pack.sources.length ? pack.sources.map(s => <div className="source-item" key={s.id}><span className="notebook-icon tone-1"><BookOpen size={20} /></span><div><h3>{s.title.replace(/Verified /g, '')}</h3><p>{s.category}</p><p className="source-excerpt">{s.excerpt||s.summary}</p></div>{s.sourceUrl && (/^(https?:\/\/|\/api\/documents\/)/i.test(s.sourceUrl)) && <a href={s.sourceUrl} target="_blank" rel="noopener noreferrer" aria-label={`Open ${s.title}`}><ExternalLink size={18} /></a>}</div>) : <EmptyTool icon={BookOpen} title="No linked sources yet" description="This notebook doesn’t contain source citations. Check important details against your course material." />}</>}
  </>;
}
